### ISSUE TITLE
[Suggestion] add extra links to the message

### ISSUE THREAD

**Issue by lewisakura** [Szmyk/mediawiki-discord#4]
This suggestion would add extra actions to the message.

For example..
`User LewisTehMinerz (contribs | talk | block) edited page Example (undo)`

**Comment by Szmyk** [comment]
Hello @LewisTehMinerz! 

Thanks for this feature request. I planned to do this feature from the beginning of development, and finally I have an excuse for this :)

Now it looks like this:

![image](https://user-images.githubusercontent.com/12484478/43423094-b890ae48-944b-11e8-85ee-c2fa6a5d261b.png)

I will push commit in few minutes.

**Comment by Szmyk** [comment]
OK, done. I also added link to edit page.

**Comment by lewisakura** [comment]
:) Thanks!
